=== danjavra/Projectes/LLMpractica16_sintesis/practica16.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT equipos (equipo+)>
<!ATTLIST equipos xmlns:xsi CDATA #REQUIRED>
<!ATTLIST equipos xsi:noNamespaceSchemaLocation CDATA #REQUIRED>
<!ELEMENT equipo (nombre_equipo,Tipo_trabajo,logros*,jugadores)>
<!ELEMENT nombre_equipo (#PCDATA)>
<!ELEMENT Tipo_trabajo (#PCDATA)>
<!ELEMENT logros (año+)>
<!ELEMENT año (exitos,fracasos)>
<!ATTLIST año id CDATA #REQUIRED>
<!ELEMENT exitos (#PCDATA)>
<!ELEMENT fracasos (#PCDATA)>
<!ELEMENT jugadores (jugador+)>
<!ELEMENT jugador (nombre,apellido,cargo,fecha_nacimiento,ruta_imagen,hora_ultimo_login,dia_ultimo_login)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT cargo (goles?,asistencias?,goles_encajados?,paradas?,robos_balon?,entradas?)>
<!ATTLIST cargo tipo CDATA #REQUIRED>
<!ELEMENT fecha_nacimiento (#PCDATA)>
<!ELEMENT ruta_imagen (#PCDATA)>
<!ATTLIST ruta_imagen tipo_imagen (jpg|png|gif) #REQUIRED>
<!ELEMENT hora_ultimo_login (#PCDATA)>
<!ELEMENT dia_ultimo_login (#PCDATA)>
<!ELEMENT goles (#PCDATA)>
<!ELEMENT asistencias (#PCDATA)>
<!ELEMENT goles_encajados (#PCDATA)>
<!ELEMENT paradas (#PCDATA)>
<!ELEMENT robos_balon (#PCDATA)>
<!ELEMENT entradas (#PCDATA)>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT __ROOT__ ANY>
<!ATTLIST __ROOT__ version CDATA #REQUIRED>

=== danjavra/Projectes/LLMpractica16_sintesis/practica16.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipos SYSTEM "practica16.dtd">

<equipos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
           xsi:noNamespaceSchemaLocation="practica16.xsd">
    <equipo>
        <nombre_equipo>Dream Team</nombre_equipo>
        <Tipo_trabajo>Equipo de Futbol sala</Tipo_trabajo>
        <logros>
            <a単o id="2015">
                <exitos>15</exitos>
                <fracasos>5</fracasos>
            </a単o>
            <a単o id="2016">
                <exitos>11</exitos>
                <fracasos>8</fracasos>
            </a単o>   
        </logros>
        <jugadores>
            <jugador>
                <nombre>Joan</nombre>
                <apellido>Ayza</apellido>
                <cargo tipo="Delantero">
                    <goles>16</goles>
                    <asistencias>2</asistencias>
                </cargo>
                <fecha_nacimiento>1982-05-05</fecha_nacimiento>
                <ruta_imagen tipo_imagen="jpg"></ruta_imagen>
                <hora_ultimo_login></hora_ultimo_login>
                <dia_ultimo_login></dia_ultimo_login>
            </jugador>
            <jugador>
                <nombre>Albert</nombre>
                <apellido>Rico</apellido>
                <cargo tipo="Portero">
                    <goles_encajados>16</goles_encajados>
                    <paradas>26</paradas>
                </cargo>
                <fecha_nacimiento>1982-10-25</fecha_nacimiento>
                <ruta_imagen tipo_imagen="jpg"></ruta_imagen>
                <hora_ultimo_login></hora_ultimo_login>
                <dia_ultimo_login></dia_ultimo_login>
            </jugador>
            <jugador>
                <nombre>Juan</nombre>
                <apellido>Ruz</apellido>
                <cargo tipo="Defensa">
                    <robos_balon>22</robos_balon>
                    <entradas>2</entradas>
                </cargo>
                <fecha_nacimiento>1987-12-03</fecha_nacimiento>
                <ruta_imagen tipo_imagen="jpg"></ruta_imagen>
                <hora_ultimo_login></hora_ultimo_login>
                <dia_ultimo_login></dia_ultimo_login>
            </jugador>
            <jugador>
                <nombre>Oriol</nombre>
                <apellido>Galan</apellido>
                <cargo tipo="Defensa">
                    <robos_balon>36</robos_balon>
                    <entradas>12</entradas>
                </cargo>
                <fecha_nacimiento>1982-06-11</fecha_nacimiento>
                <ruta_imagen tipo_imagen="jpg">logo.jpg</ruta_imagen>
                <hora_ultimo_login></hora_ultimo_login>
                <dia_ultimo_login></dia_ultimo_login>
            </jugador>
            <jugador>
                <nombre>Cristian</nombre>
                <apellido>Siles</apellido>
                <cargo tipo="Delantero">
                    <goles>20</goles>
                    <asistencias>13</asistencias>
                </cargo>
                <fecha_nacimiento>1992-05-20</fecha_nacimiento>
                <ruta_imagen tipo_imagen="jpg"></ruta_imagen>
                <hora_ultimo_login></hora_ultimo_login>
                <dia_ultimo_login></dia_ultimo_login>
            </jugador>
        </jugadores>
    </equipo>
    
</equipos>
